version: '3.8'
services:
  db-data:
    image: mysql
    container_name: db_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db-data
    ports:
      - "8741:80"
    environment:
      PMA_HOST: db-data
      PMA_ARBITRARY: 1
    networks:
      - dev

  react-ui:
    build:
      context: ./Joke_bot
    ports:
      - "3000:3000"
    container_name: react-ui
    restart: always
    stdin_open: true
    volumes:
      - ./Joke_bot:/usr/src/app/Joke_bot
      - /usr/src/app/Joke_bot/node_modules

  express-app:
    build:
      context: ./api
    ports:
      - "8080:8080"
    container_name: api
    restart: always
    stdin_open: true
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    depends_on:
      - db-data
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
